// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	User
	UserGetRequest
	UserPostRequest
	UserResponse
	UserAuthRequest
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Hash  string `protobuf:"bytes,3,opt,name=hash" json:"hash,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type UserGetRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *UserGetRequest) Reset()                    { *m = UserGetRequest{} }
func (m *UserGetRequest) String() string            { return proto.CompactTextString(m) }
func (*UserGetRequest) ProtoMessage()               {}
func (*UserGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserGetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserPostRequest struct {
	User     *User  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *UserPostRequest) Reset()                    { *m = UserPostRequest{} }
func (m *UserPostRequest) String() string            { return proto.CompactTextString(m) }
func (*UserPostRequest) ProtoMessage()               {}
func (*UserPostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserPostRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserPostRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *UserResponse) Reset()                    { *m = UserResponse{} }
func (m *UserResponse) String() string            { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()               {}
func (*UserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserAuthRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *UserAuthRequest) Reset()                    { *m = UserAuthRequest{} }
func (m *UserAuthRequest) String() string            { return proto.CompactTextString(m) }
func (*UserAuthRequest) ProtoMessage()               {}
func (*UserAuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserAuthRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserAuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*UserGetRequest)(nil), "UserGetRequest")
	proto.RegisterType((*UserPostRequest)(nil), "UserPostRequest")
	proto.RegisterType((*UserResponse)(nil), "UserResponse")
	proto.RegisterType((*UserAuthRequest)(nil), "UserAuthRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	Add(ctx context.Context, in *UserPostRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Get(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*User, error)
	Update(ctx context.Context, in *UserPostRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Delete(ctx context.Context, in *UserPostRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Auth(ctx context.Context, in *UserAuthRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Add(ctx context.Context, in *UserPostRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/UserService/add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Get(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/UserService/get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *UserPostRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/UserService/update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Delete(ctx context.Context, in *UserPostRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/UserService/delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Auth(ctx context.Context, in *UserAuthRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/UserService/auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	Add(context.Context, *UserPostRequest) (*UserResponse, error)
	Get(context.Context, *UserGetRequest) (*User, error)
	Update(context.Context, *UserPostRequest) (*UserResponse, error)
	Delete(context.Context, *UserPostRequest) (*UserResponse, error)
	Auth(context.Context, *UserAuthRequest) (*UserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Add(ctx, req.(*UserPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*UserGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*UserPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Delete(ctx, req.(*UserPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Auth(ctx, req.(*UserAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add",
			Handler:    _UserService_Add_Handler,
		},
		{
			MethodName: "get",
			Handler:    _UserService_Get_Handler,
		},
		{
			MethodName: "update",
			Handler:    _UserService_Update_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _UserService_Delete_Handler,
		},
		{
			MethodName: "auth",
			Handler:    _UserService_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0x80, 0xff, 0xb4, 0x69, 0xf9, 0x9d, 0x5a, 0x2b, 0x4b, 0x91, 0x18, 0x2a, 0xc8, 0xea, 0x41,
	0x2a, 0x64, 0xb1, 0xde, 0xea, 0xc5, 0x82, 0xa0, 0x07, 0x0f, 0x12, 0xf1, 0x01, 0x56, 0x33, 0x24,
	0x81, 0x24, 0x1b, 0xb3, 0x9b, 0x7a, 0x10, 0x2f, 0xbe, 0x82, 0xaf, 0xe2, 0x9b, 0xf8, 0x0a, 0x3e,
	0x88, 0xec, 0x26, 0x94, 0xa6, 0x94, 0xea, 0x6d, 0x77, 0xe7, 0x9b, 0x99, 0x6f, 0x86, 0x05, 0x28,
	0x25, 0x16, 0x5e, 0x5e, 0x08, 0x25, 0xdc, 0x51, 0x28, 0x44, 0x98, 0x20, 0xe3, 0x79, 0xcc, 0x78,
	0x96, 0x09, 0xc5, 0x55, 0x2c, 0x32, 0x59, 0x45, 0xe9, 0x15, 0xd8, 0x0f, 0x12, 0x0b, 0x42, 0xc0,
	0xce, 0x78, 0x8a, 0x8e, 0x75, 0x68, 0x9d, 0x6c, 0xf9, 0xe6, 0x4c, 0x86, 0xd0, 0xc1, 0x94, 0xc7,
	0x89, 0xd3, 0x32, 0x8f, 0xd5, 0x45, 0x93, 0x11, 0x97, 0x91, 0xd3, 0xae, 0x48, 0x7d, 0xa6, 0xc7,
	0xb0, 0xa3, 0xab, 0x5c, 0xa3, 0xf2, 0xf1, 0xb9, 0x44, 0xa9, 0xd6, 0xd5, 0xa3, 0x37, 0x30, 0xd0,
	0xd4, 0x9d, 0x90, 0x0b, 0x6c, 0x1f, 0x6c, 0xad, 0x6a, 0xb0, 0xde, 0xa4, 0xe3, 0xe9, 0xb8, 0x6f,
	0x9e, 0x88, 0x0b, 0xff, 0x73, 0x2e, 0xe5, 0x8b, 0x28, 0x82, 0x5a, 0x60, 0x71, 0xa7, 0x14, 0xb6,
	0x0d, 0x89, 0x32, 0x17, 0x99, 0xc4, 0xb5, 0xdd, 0x66, 0x55, 0xb7, 0x59, 0xa9, 0xa2, 0x0d, 0x52,
	0x9b, 0xda, 0x4c, 0x3e, 0x5b, 0xd0, 0xd3, 0x35, 0xee, 0xb1, 0x98, 0xc7, 0x4f, 0x48, 0x2e, 0xa1,
	0xcd, 0x83, 0x80, 0xec, 0x7a, 0x2b, 0x63, 0xb8, 0x7d, 0x6f, 0x59, 0x87, 0x3a, 0xef, 0x5f, 0xdf,
	0x1f, 0x2d, 0x42, 0xfb, 0x6c, 0x7e, 0xc6, 0x30, 0x15, 0x8a, 0xe9, 0x89, 0xa6, 0xd6, 0x98, 0x5c,
	0x40, 0x3b, 0x44, 0x45, 0x06, 0x5e, 0x73, 0x5d, 0x6e, 0x35, 0x39, 0x1d, 0x99, 0xc4, 0x3d, 0x32,
	0x6c, 0x24, 0xb2, 0x57, 0x6d, 0xfa, 0x46, 0x4e, 0xa1, 0x5b, 0xe6, 0x01, 0x57, 0xf8, 0xbb, 0xc1,
	0x3f, 0x0d, 0x07, 0x98, 0xe0, 0xdf, 0xe0, 0x5b, 0xb0, 0x79, 0xa9, 0xa2, 0x1a, 0x5d, 0x5a, 0xd9,
	0x2a, 0x7a, 0x64, 0x04, 0x0f, 0xa8, 0xd3, 0x10, 0xd4, 0xb9, 0xb5, 0xe4, 0xd4, 0x1a, 0x3f, 0x76,
	0xcd, 0xd7, 0x3a, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xee, 0xb5, 0x4a, 0x86, 0x02, 0x00,
	0x00,
}
